services:
  dev:
    env_file: .env

    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
      args:
        ROS_DISTRO: ${ROS_DISTRO}
    image: adi_ros2:${ROS_DISTRO}-dev

    volumes:
      # Mount the workspace into the container
      - .:/adi_ros2_ws:cached
      # HW Access
      - /dev:/dev

    # Network & IPC
    network_mode: host
    ipc: host
    pid: host

    # Hardware access (Narrow this down to specific devices if your security policy requires it)
    privileged: true
    group_add:
      - dialout # For USB serial access

    # Interactivity
    stdin_open: true
    tty: true
