name: Generate documentation
on:
    push:
      branches:
        - humble
      tags:
        - v*.*.*
    pull_request:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        persist-credentials: false
        token: ${{ env.GH_TOKEN }}
        submodules: true

    - name: Set up Python3 environment
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install pip packages
      working-directory: src/adi_ros2/doc
      run: |
        pip install pip --upgrade
        pip install -r requirements.txt

    - name: Build doc
      working-directory: ci
      run: |
        export ADOC_DOC_VERSION=${{ github.ref_name }}
        export DOC_REPOSITORY=adi_ros2
        ./build_doc.sh

    - name: Store the generated doc
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: _build/docs_output

  deploy-doc:
    runs-on: ubuntu-latest
    needs: build-doc
    # Extend the job with future ROS2 releases
    if: github.ref == 'refs/heads/humble'

    steps:
    - uses: actions/checkout@v4
    - run: |
        git config --global user.name "${{ github.event.head_commit.committer.name }}"
        git config --global user.email "${{ github.event.head_commit.committer.email }}"

    - name: Save the trigger branch name
      run: |
        branch_name=$(git rev-parse --abbrev-ref HEAD)
        echo "branch_name=$branch_name" >> $GITHUB_ENV

    - name: Prepare gh-pages branch
      run: |
        git reset --hard ;
        git clean -fdx ;

        gh_pages_exists=$(git ls-remote --exit-code --heads origin refs/heads/gh-pages || echo "false")

        if [ "$gh_pages_exists" = "false" ]; then
          echo "Creating gh-pages branch"
          git checkout --orphan gh-pages ;
          git reset --hard;
          git commit -m "initial commit" --allow-empty
        else
          echo "Working on existing gh-pages branch"
          git fetch origin gh-pages ;
          git checkout -b gh-pages origin/gh-pages ;
        fi

    - name: Overwrite existing doc
      run: |
        if [ -d "${branch_name}" ]; then
          echo "Removing existing directory ${branch_name}"
          git rm -r ${branch_name} --quiet || true
        fi

    - name: Save generated doc
      uses: actions/download-artifact@v4
      with:
        path: ${{ env.branch_name }}
        name: html

    - name: Generate tags for the versioned directories
      run: |
        echo "{" > tags_unsorted.json
        find . -type d -mindepth 2 -maxdepth 2 ! -name ".*" ! -path "*/.git*" ! -path . | sort | \
        awk -F/ '
        BEGIN {first=1}
        {
            # Only second level directories
            path = $2 "/" $3

            if ($3 == "adi_meta") {
                name = $2
                label = "core"
            } else {
                name = $2 " > " $3
                label = ""
            }

            # Skip empty entries
            if (path != "") {
                if (!first) printf ",\n"
                printf "  \"%s\": [\"%s\", \"%s\"]", path, name, label
                first=0
            }
        }' >> tags_unsorted.json
        echo -e "\n}" >> tags_unsorted.json

        # Sort using the name field in the tags.json as the key
        jq '
          to_entries |
          sort_by(.value[0]) |
          from_entries
        ' tags_unsorted.json > tags.json
        rm tags_unsorted.json


    - name: Generate auxiliary files
      run: |
        [ -d "_sources" ] && rm -rf _sources
        touch .nojekyll

        # Link the index of the versioned directory to the adi_meta/index.html
        printf '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=adi_meta/index.html"></head><body></body></html>' > ${branch_name}/index.html

        # Create a redirecting index.html at the root of the gh-pages branch to the latest branch
        printf '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=%s/index.html"></head><body></body></html>' "${branch_name}" > index.html

    - name: Commit gh-pages
      run: |
        git add . >> /dev/null
        git commit -m "deploy: ${GITHUB_SHA}" --allow-empty

    - name: Push to gh-pages
      run: |
        git push origin gh-pages:gh-pages